// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIX9NHMk4rAkLWbciLZclXV6JmfAWa3ZE',
    appId: '1:246994578596:web:1021db4f60fb69f9590a31',
    messagingSenderId: '246994578596',
    projectId: 'otp1-c75e9',
    authDomain: 'otp1-c75e9.firebaseapp.com',
    storageBucket: 'otp1-c75e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmedmJGqpeQfLUIzyZrhsHonhzxTY73RA',
    appId: '1:246994578596:android:2e9a97e02cb5d739590a31',
    messagingSenderId: '246994578596',
    projectId: 'otp1-c75e9',
    storageBucket: 'otp1-c75e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IMwbiaMkk1k4PCStFFwGJJE7P9R7x1U',
    appId: '1:246994578596:ios:c47dc0026a40069b590a31',
    messagingSenderId: '246994578596',
    projectId: 'otp1-c75e9',
    storageBucket: 'otp1-c75e9.appspot.com',
    iosClientId: '246994578596-l3qqh6g1mdsrlub96ro5vahekprai64a.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneauthFirebase',
  );
}
